version: "3.5"

services:
  dind-server:
    container_name: dind-server
    # privileged: true
    build: ./server
    # command: --storage-driver=overlay2 --group 1000
    restart: unless-stopped
    networks:
      - local
    expose:
      - 80
      - 2375
      - 2376
    volumes:
      - ./www:/www
    environment:
      - WWW_PATH=/www
      - DOCKER_HOST=tcp://dind-with-compose:2375

  dind-with-compose:
    container_name: dind-with-compose
    image: cheshirecode/dind-with-compose
    privileged: true
    build: ./dind-with-compose
    command: --storage-driver=overlay2 --group 1000
    volumes:
      - /tmp/var/lib/docker:/var/lib/docker
    networks:
      - local

networks:
  local:
    driver: bridge
    external: true